### ISSUE TITLE
x-ui的web端不显示

### ISSUE THREAD

**Issue by ifyz** [Lynn-Becky/Alpine-x-ui#2]
任何由于自己的配置错误导致的情况，请自行解决，issues 只用于解决面板自身的 bug

如果你确定面板的功能实现有 bug，请尽可能提供更多更精确的描述信息、复现方法与复现结果等等，而不是草草一句话了事，这对于问题的解决没有帮助

提问的艺术: https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md

首页仅能显示标题，html代码的内容不完整，脚本重装后无效。

`
    <a-input v-model.trim="user.username" placeholder='m`

这后面就没有内容了，不是完整的html

**Comment by Lynn-Becky** [comment]
先尝试重装小鸡，再重装脚本，脚本已经更新v0.2

**Comment by Lynn-Becky** [comment]
若还是有问题，则等待我同步更新v0.3.4.4的二进制文件
