### ISSUE TITLE
能不能添加SSL证书申请

### ISSUE THREAD

**Issue by travis-tang** [Lynn-Becky/Alpine-x-ui#3]
非常感谢提供这么好的脚本，请问能不能添加回原版对SSL证书申请的功能呢？

**Comment by Lynn-Becky** [comment]
会考虑增加，就是alpine的nat机配置差，ip一般都是樯的，所以把这个功能给删了

**Comment by Lynn-Becky** [comment]
更好了，更新或者重装一下xui

**Comment by travis-tang** [comment]
> 更好了，更新或者重装一下xui

非常感谢！
